### ISSUE TITLE
Set day

### ISSUE THREAD

**Issue by Xeyos88** [demarchisd/stacked-gantt#1]
Hi,
is it possible to set the day? Or the gantt is created ever related with the current day?

**Comment by demarchisd** [comment]
Hello!

Sorry I didn't write the documentation yet, but the gantt is created according to the activities and markers params. So, for example, if you pass a list of activities and the sooner of them is 7/10 10am and the later is 7/11 10am, the gantt will be created from 7/10 10am to 7/11 10am.

The date information is not displayed by default, but you can make it appear above the hours information setting the `showDateOnHeader` to `true` inside the `style` option (you can see it in the examples files).

**Comment by Xeyos88** [comment]
Hello!
Thanks for the quick response, but from the examples I'm not clear whether you can set as a date / time parameter or just the hour.
I see:
```javascript
begin: createDate('23:45'), end: createDate('02:00', 1)
```

**Comment by demarchisd** [comment]
Hi!

The `createDate` is just a helper function to return a `Date` based on the current day, but you could pass any `Date` object to it:

```
let begin = new Date();
begin.setHours("10");

let end = new Date();
end.setHours(11);
end.setMinutes(30);
end.setDate(end.getDate()+1);

......

begin: begin, end: end
```
