### ISSUE TITLE
update function

### ISSUE THREAD

**Issue by owldrak** [demarchisd/stacked-gantt#15]
hey, nice plugin!

Whenever we call update() function, it actually re-builds whole gantt, like with all HTML emptied and redrawn.

Is there a way to just update activities without rebuilding from zero? The point is, if activities are added dynamically, the chart keeps flashing and jumping to the top. Would appreciate any advice.

**Comment by demarchisd** [comment]
Hi Oliver!

Unfortunately there's no native way for doing that :( It'd be a cool enhancement - in case you implement it, please send a PR and I'll merge it!

A possible hack would be building the updated gantt in a hidden div and then replace the old one with it afterwards.

**Comment by owldrak** [comment]
For now did it with basic setInterval to update chart. As data is arriving every 5 seconds, was really annoying :) That helped.
