### ISSUE TITLE
Import data from saprate json file

### ISSUE THREAD

**Issue by vaibhav12aggarwal** [demarchisd/stacked-gantt#2]
Hi
I want to import data from seprate json file.please help me how can i do..

**Comment by demarchisd** [comment]
Hi!

You could use [jQuery's `getJSON` function](http://api.jquery.com/jquery.getjson/) for loading the data from a separate JSON file.

**Comment by vaibhav12aggarwal** [comment]
Hi demarchisd

I want the whole chart to appear in a smaller div therefore I need to decrease the width of "sg_time_header_item" for each hour to almost half of it.  Please suggest.

Regards,
Vaibhav.

**Comment by demarchisd** [comment]
Hi,

Please try setting the `hourWidth` option to a smaller value like `40` (value represented in px).

E.g.:

```js
var options = {
    data: [...yourdata],
    style: {
       hourWidth: 40
    }
}

$("#your-div").stackedGantt(options)
```

**Comment by vaibhav12aggarwal** [comment]
Hi Demarchisd 

Thanks for the brillent reply. This has solved my problem.
Further, I intend to make changes in tooltip:
1. Move  sg_tooltip_title downwords and move  sg_tooltip_description upwords.
2. Add more contents from my database to tooltip

Can you please help me with this.
Regards,
Vaibhav Aggarwal

**Comment by demarchisd** [comment]
Hi vaibhav12aggarwal!

I'm glad that solved your problem. 

About the tooltip customization: unfortunately there's no way to do that yet. Could you open another issue requesting the development of this item, please? Then I'll develop it as soon as possible. 

Though, if you're in a hurry, you could fork the project and customize the tooltip yourself (check the `appendTooltipContent` function in `src/jquery.stacked-gantt.js` file).

Please let me know if you need anything else.
