### ISSUE TITLE
For fictitious entry when data is not in required form

### ISSUE THREAD

**Issue by vaibhav12aggarwal** [demarchisd/stacked-gantt#3]
Hi Demarchisd,
I want to know that,when data is not in required form, I want to show fictitious entry like - "Your planing is here".but when data comes in required form  fictitious entry must be removed.How can i do this?
Thanks&regards
Vaibhav aggarwal

**Comment by vaibhav12aggarwal** [comment]
Hi Demarchisd,
I found something "noData Text".this is occupying space but no data show.how can i fix it.
Thanks&regards
Vaibhav aggarwal

**Comment by demarchisd** [comment]
Hello @vaibhav12aggarwal !

If you build the stackedGantt passing an empty array for the `data` parameter, the text `'No data to display.'` will be shown automatically. You can customize the text using the `noDataText` option inside the style attribute.

For example:

```js
const myStackedGanttInstance = $("#gantt").stackedGantt({
   data: [],
   style: {
      noDataText: 'Your planing is here'
   }
});
```

After that, you can update the chart with your actual data using the `update` function:

```js
myStackedGanttInstance.update({
   data: myDataArray
})
```

where `myDataArray` is an array following the [`data`](https://github.com/demarchisd/stacked-gantt#data) specs
