### ISSUE TITLE
var data = [] from ajax errors

### ISSUE THREAD

**Issue by michalchrzastek** [demarchisd/stacked-gantt#7]
Hello,
I'm trying to replace the static var data=[] with SQL output, I have generated the output layout to match your structure. If I copy/paste the generated output into var data[] it works, but when I do this:

```
var data = $.ajax({
          url: "../GetData_DropDown/getdata_PRODschedule.php",
          dataType: "json",
          async: false
        }).responseText;
```

```
Uncaught TypeError: n.forEach is not a function
    at w (jquery.stacked-gantt.min.js:5)
    at o.config (jquery.stacked-gantt.min.js:5)
    at init.n.fn.stackedGantt (jquery.stacked-gantt.min.js:5)
    at HTMLDocument.<anonymous> (ldlfoverview.php:274)
    at fire (jquery.js:1017)
    at Object.fireWith [as resolveWith] (jquery.js:1127)
    at Function.ready (jquery.js:416)
    at HTMLDocument.DOMContentLoaded (jquery.js:92)
```

Any suggestions please?

**Comment by demarchisd** [comment]
Hello Michal!

I guess that the `responseText` property is a string, and you need to transform it to an object. Check if there's any `responseJSON` property instead of `responseText` and try to use it. 

If there isn't, try to parse it with `JSON.parse(data)`.

Hope it helps!

**Comment by michalchrzastek** [comment]
Hello,

I have tried those already before seeking help here.

`.responseJSON` produces the same error,
`.JSON.parse(data)` produces this:

```
Uncaught TypeError: Cannot read property 'parse' of undefined
    at ldlfoverview.php:288
```

**Comment by demarchisd** [comment]
Actually, the JSON.parse would be something like this:

```js
var data = $.ajax({
          url: "../GetData_DropDown/getdata_PRODschedule.php",
          dataType: "json",
          async: false
        }).responseText;

data = JSON.parse(data);
```

**Comment by michalchrzastek** [comment]
oh sorry,

now the error has changed to:

```
Uncaught SyntaxError: Unexpected token d in JSON at position 3
    at JSON.parse (<anonymous>)
    at ldlfoverview.php:721
```
the 'd' is the very first  d in 'description'

**Comment by demarchisd** [comment]
Could you post here the contents of `responseText` and `responseJSON`, please?

**Comment by michalchrzastek** [comment]
var data = $.ajax({
          url: "../_getData/getdata_PRODschedule.php",
          dataType: "json",
          async: false
          //}).responseText;
          }).responseJSON;
data = JSON.parse(data);

![responsejson](https://user-images.githubusercontent.com/38867528/39534813-63e1a580-4e2a-11e8-8038-98899e8147f5.JPG)
![responsetext](https://user-images.githubusercontent.com/38867528/39534817-63ff9d6a-4e2a-11e8-98e5-01d795cf3d8d.JPG)



OR the content i'm producing from SQL?

**Comment by demarchisd** [comment]
Oh, I can see the reason it's not working. The content is not a valid JSON. You need to have double quotes on the attributes and in the string values, too. For example:

```js
[{"description": "LDF1"}]
```

Please refer to this link for more information: https://www.json.org/

**Comment by michalchrzastek** [comment]
oh I see. Excellent!
One more tip please around 'begin' and 'end'

, "begin": new Date("'.$row["startTime"].'"),

how to use quotes around this?


ok, got it:
` , "begin": "new Date('.$row["startTime"].')",`

now when I produce foreach loop, i'm ending up with a comma at the end, how can I get rid of the very last one?

**Comment by demarchisd** [comment]
Hello Michal,

Did you find out how to resolve your problem? 

I'm closing this thread, if you have any other doubt, please feel free to create another issue.
