### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by michalchrzastek** [demarchisd/stacked-gantt#8]
Hello again,

What date format do I need to pass through JSON?

In your example there is:
 `begin: new Date('2018-05-27T16:40:31'),` 
this works hardcoded but when I take date from SQL and place it into JSON gives me this:
`,"begin":"new Date('.$row["startTime"].')", where format follows yyyy-mm-ddThh:mm:ss`
![capture](https://user-images.githubusercontent.com/38867528/40587632-cfc3bd62-61c9-11e8-99f9-5b12c72e8d6d.JPG)

then I get this error:

`Uncaught Error: Invalid Date: new Date(2018-05-27T15:55:31)`

**Comment by demarchisd** [comment]
Hello Michal!

Actually the way you're passing the parameter is generating a string with the content `new Date(2018-05-27T15:55:31)`. It should be something like this:

`,"begin":new Date("'.$row["startTime"].'")`

Please let me know if it works for you!

**Comment by michalchrzastek** [comment]
Hello, 

Ok, THis gives another error:
```
Uncaught SyntaxError: Unexpected token e in JSON at position 162
    at JSON.parse (<anonymous>)
    at ldlfoverview.php:102
```
and highlights the first 'new', in new Date

**Comment by demarchisd** [comment]
Hmm, could you post the hole code for me to have a better idea of the context?

**Comment by michalchrzastek** [comment]
is this enough?

```
              $j=0;
              foreach($resultSchedule as $row){
                echo '{"code":"DGR","description":"'.$row["descr"].'\nFPC:'.$row["fpc"].'\nPO:'.$row["po"].'\nBATCH:'.$row["BatchID"].'","begin":new Date("'.$row["startTime"].'"),"end":new Date("'.$row["endTime"].'")}';
                if($j != $lenSchedule - 1){echo ',';}
                $j++;
              }
```
From SQL:
$row["startTime"] -> this is a date in this format: yyyy-mm-ddThh:mm:ss

**Comment by demarchisd** [comment]
When do you call `JSON.parse`?

**Comment by michalchrzastek** [comment]
the previous post is in file _getData/getdata_PRODschedule.php

```
var data = $.ajax({
          url: "../_getData/getdata_PRODschedule.php",
          dataType: "json",
          async: false
          }).responseText;
data = JSON.parse(data);
```

when I use json validator, it  fails with current setup "begin": new Date ("....")
was ok when I had "begin":"new Date()"

**Comment by demarchisd** [comment]
Oh, I get it. Actually you'll have to keep them as a string before parsing to JSON and update them to a Date object after it. Also, you can't have a `\n` char when parsing a JSON.

```
              $j=0;
              foreach($resultSchedule as $row){
                echo '{"code":"DGR","description":"'.$row["descr"].'FPC:'.$row["fpc"].'PO:'.$row["po"].'BATCH:'.$row["BatchID"].'","begin": "'.$row["startTime"].'","end": "'.$row["endTime"].'"}';
                if($j != $lenSchedule - 1){echo ',';}
                $j++;
              }
```

```js
var data = $.ajax({
          url: "../_getData/getdata_PRODschedule.php",
          dataType: "json",
          async: false
          }).responseText;

data = JSON.parse(data);

data.forEach(activity => {
        activity.begin = new Date(activity.begin);
        activity.end = new Date(activity.end);
});

```

**Comment by michalchrzastek** [comment]
O, I see. However this gives the same error:
`Uncaught Error: Invalid Date: 2018-05-28T22:53:08`
JSON validator is OK, no errors.
![capture](https://user-images.githubusercontent.com/38867528/40664126-24956d98-6352-11e8-9103-a209a02d33e9.JPG)

**Comment by demarchisd** [comment]
There must be some other `Date` that you should parse, either. Do you have any `Markers` or `Thresholds`? Debug the `options` variable and check where you have a date that's a string. Then replace it with a new `Date`.

**Comment by michalchrzastek** [comment]
This is full script:
`   <script type="text/javascript">

    function createDate(time, daysToSum)
    {
      var split = time.split(':');
      var ret = new Date();
      ret.setHours(split[0]);
      ret.setMinutes(split[1]);

      if(daysToSum) ret.setDate(ret.getDate()+1);
      return ret;
    }

 var data = $.ajax({
          url: "../_getData/getdata_PRODschedule.php",
          dataType: "json",
          async: false
          }).responseText;

 data = JSON.parse(data);

 data.forEach(activity => {
        activity.begin = new Date(activity.begin);
        activity.end = new Date(activity.end);
 });

    var generalMarkers = [
        { description: "Current Time", when: Date.now(), color: "#e942cd", width: "5px",
          onClick: function(marker) {
            alert('Very important! - '+marker.description);
          }
        }
    ];

    var options = {
      data: data,
      generalMarkers: generalMarkers,
      style: {
        months: ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'],
        activityStyle: {
          'IDL': { color: "#000000", height: "30px" }, // IDLE
          'LEM': { color: "#e5dd00" }, //LEMON
          'APP': { color: "#12e000" }, //APPLE
          'RED': { color: "#e00000" }, //RED
          'PNK': { color: "#e000c2" }, //PINK
          'DGR': { color: "#105900" }, //DARK GREEN

        },
        showDateOnHeader: true,
        dateHeaderFormat: function(date)
        {
          var days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
          var months = ['January','February','Martch','April','May','June','July','August','September','October','November','December'];

          return days[date.getDay()] + ", " + months[date.getMonth()] + " " + date.getDate() +"th - " + date.getFullYear();
        },
        descriptionContainerWidth: '100px'
      }
    };

    $(document).ready(function() {
      var $timeline = $('#timeline').stackedGantt(options);
    });


  </script>`

**Comment by demarchisd** [comment]
Ok, so your `data` var is actually holding all the rows informations. Try this:

```js
data.forEach(row => row.activities.forEach(activity =>
{
	activity.begin = new Date(activity.begin);
	activity.end = new Date(activity.end);
}));
````

**Comment by michalchrzastek** [comment]
Excellent. This works!
Thank you for your support

**Comment by demarchisd** [comment]
You're welcome!
